version: '3'

services:
  db: 
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - network-node

  app:
    build:
      context: ./js
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: "node index.js"
    volumes:
      - ./js:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    networks:
      - network-node
    depends_on:
      - db
  
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    tty: true
    ports:
      - "8080:80"
    networks:
      - network-node
    depends_on:
      - app

networks:
  network-node:
    driver: bridge